'use client'
import{Bell,User,X,LogOut}from'lucide-react'
import Image from'next/image'
import{useApp}from'@/lib/app-context'
import{Page}from'@/lib/types'
import{MobileMenuButton}from'./sidebar'
import{format}from'date-fns'
import{ptBR}from'date-fns/locale'
import{getNotifications}from'@/lib/utils-app'
import{useState}from'react'
const titles:Record<Page,string>={login:'Login',dashboard:'Dashboard',calendario:'Calendário',cadastrar:'Cadastrar Festa',lista:'Lista de Festas',pesquisa:'Pesquisar',exportar:'Exportar PDF',configuracoes:'Configurações',detalhes:'Detalhes da Festa','admin-notificacoes':'Notificações',atendimentos:'Atendimentos'}
export function Header({onMenuClick}:{onMenuClick:()=>void}){const{currentPage,festas,logout}=useApp();const notifs=getNotifications(festas),[showNotifs,setShowNotifs]=useState(false),[showUser,setShowUser]=useState(false);const today=format(new Date(),"EEEE, d 'de' MMMM 'de' yyyy",{locale:ptBR});return <header className="sticky top-0 z-10 flex items-center justify-between gap-2 border-b bg-card px-3 py-2.5 shadow-sm sm:px-4 sm:py-3"><div className="flex items-center gap-2 min-w-0"><MobileMenuButton onClick={onMenuClick}/><div><h1 className="text-base sm:text-lg font-bold truncate">{titles[currentPage]}</h1><p className="hidden sm:block text-xs text-muted-foreground capitalize">{today}</p></div></div><div className="flex items-center gap-1.5"><div className="lg:hidden"><Image src="/logo.png" alt="Buffet Agathon" width={28} height={28} className="object-contain"/></div><div className="relative"><button onClick={()=>{setShowNotifs(!showNotifs);setShowUser(false)}} className="relative p-2 rounded-xl hover:bg-muted"><Bell size={18} className="text-muted-foreground"/>{notifs.length>0&&<span className="absolute top-1 right-1 h-2 w-2 rounded-full bg-teal-500"/>}</button>{showNotifs&&<div className="fixed inset-x-3 top-16 z-50 sm:absolute sm:inset-x-auto sm:right-0 sm:top-full sm:mt-2 sm:w-80 rounded-2xl border bg-card shadow-2xl overflow-hidden"><div className="flex justify-between p-3 bg-teal-800 text-white"><b className="text-sm">Notificações</b><button onClick={()=>setShowNotifs(false)}><X size={16}/></button></div>{notifs.length===0?<p className="p-4 text-sm text-center text-muted-foreground">Sem notificações</p>:<div className="max-h-72 overflow-y-auto">{notifs.map((n,i)=><p key={i} className="p-3 text-sm border-b last:border-0">{n.message}</p>)}</div>}</div>}</div><div className="relative"><button onClick={()=>{setShowUser(!showUser);setShowNotifs(false)}} className="flex items-center gap-1.5 rounded-xl bg-teal-700 px-2.5 py-2 text-white"><User size={15}/><span className="hidden sm:block text-xs font-bold">Edna</span></button>{showUser&&<div className="absolute right-0 top-full mt-2 w-40 rounded-xl border bg-card p-1.5 shadow-xl"><div className="px-3 py-2 text-xs text-muted-foreground">Edna</div><button onClick={()=>logout()} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-600 hover:bg-red-50"><LogOut size={16}/>Sair</button></div>}</div></div></header>}
